### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by manatarms** [glemaitre/traffic-sign-detection#5]
I'm getting this error when I try to run make. Any ideas why?

`make:** No targets specified and no makefile found. Stop.`
I'm running Mint 18
Any ideas why? 

Thanks.

**Comment by glemaitre** [comment]
Because you don't have a `Makefile`.
You need to run `cmake` first which will create a `Makefile` and then use `make` command.

Check this [section](https://github.com/glemaitre/traffic-sign-detection#compilation) of the README file

**Comment by manatarms** [comment]
Thanks for your reply. Looks like I forgot to compile the gtest library. Sorry about asking you this here since it's not an issue but Any pointers on using this for videos?

**Comment by glemaitre** [comment]
Yep there is some potential. This is not my main research right now so I could not push it as I would have like. For video, you just need to split the stream into images. However, the algorithm is still not real time and it is where there is room for improvements.

In fact the optimization is not bounded and a large amount of time could be gain by bounding the parameters. Also, because we try to fit the 4 type of signs, some of them will go really wrong and time will be spend for results that will be discarded afterwords. Furthermore, this is performed in a sequence. So the following things can be done: 
- bound the optimization,
- perform the 4 optimizations in parallel,
- make an early stop when things go side ways.

**Comment by manatarms** [comment]
Thanks so much. I really appreciate it. I will let you know what I come up with. Cheers
